version: '3.9'
services:
  user-service:
    build:
      context: ./User_Services
      dockerfile: Dockerfile
    container_name: user_service_container
    volumes:
      - ./User_Services:/code
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    networks:
      - my-api-net  

  postgres_db:
    image: postgres:latest
    restart: always
    container_name: PostgresCont
    environment:
      POSTGRES_USER: ziakhan
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - my-api-net

volumes:
  postgres_db:
    driver: local

networks:
  my-api-net:  # Define the custom network
